# Generated by Django 3.2.25 on 2025-04-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.CharField(choices=[('20', '20 min'), ('30', '30 min'), ('60', '60 min')], default='30', max_length=3),
            preserve_default=False,
        ),
    ]
