# Generated by Django 5.2 on 2025-04-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_alter_booking_duration_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(choices=[('15', '15 min'), ('30', '30 min'), ('60', '60 min')]),
        ),
    ]
