# Generated by Django 5.2 on 2025-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0006_booking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(choices=[(15, '15 min'), (30, '30 min'), (60, '60 min')]),
        ),
    ]
