# Generated by Django 5.2 on 2025-04-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0007_alter_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reading_type',
            field=models.CharField(choices=[('tarot', 'Tarot Reading'), ('rune', 'Rune Reading'), ('oracle', 'Oracle Reading')], max_length=100),
        ),
    ]
