# Generated by Django 5.2 on 2025-04-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_fix_country_field'),
        ('accounts', '0009_fix_country_values'),
    ]

    operations = [
    ]
