# Generated by Django 5.2 on 2025-04-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_country'),
        ('checkout', '0006_fix_order_country_values'),
    ]

    operations = [
    ]
