# Generated by Django 5.2 on 2025-04-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_merge_20250422_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='session_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
