# Generated by Django 5.2 on 2025-04-17 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycarddraw',
            name='drawn_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
