# Generated by Django 3.2.25 on 2025-04-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_tarotcard_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotcard',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='products.product'),
        ),
        migrations.AlterField(
            model_name='tarotcard',
            name='categories',
            field=models.ManyToManyField(related_name='tarot_cards', to='products.Category'),
        ),
    ]
