# Generated by Django 3.2.25 on 2025-04-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20250413_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotcard',
            name='categories',
            field=models.ManyToManyField(related_name='tarot_cards', to='products.Category'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
