# Generated by Django 5.2 on 2025-04-30 09:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dmz8aasls/image/upload/default.png', max_length=255, verbose_name='image'),
        ),
    ]
